apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
  namespace: ai-remediation

spec:
  replicas: 1

  selector:
    matchLabels:
      app: broken-app

  template:
    metadata:
      labels:
        app: broken-app

    spec:
      containers:
      - name: broken-app

        image: nginx:latest

        command: ["/bin/sh"]

        args:
          - -c
          - |
            echo "Starting app..."
            sleep 5
            exit 1