apiVersion: v1
kind: Service

metadata:
  name: monitor-agent
  namespace: ai-remediation

  labels:
    app: monitor-agent

spec:
  selector:
    app: monitor-agent

  ports:
  - name: metrics
    port: 8000
    targetPort: 8000